name: C++ Build

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 30
    container:
      image: ghcr.io/njm08/seeplusplus-opencv:latest
      options: --user root # TODO Workaround for now, since the git checkout does not work otherwise.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Build Release
        run: python3 tools/build_scripts/build_local_release.py

      - name: Build Debug
        run: python3 tools/build_scripts/build_local_debug.py