name: Build C++ Project

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # required to push to GHCR

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build & push Docker image with cache to GHCR
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/cpp-build:latest
            ghcr.io/${{ github.repository }}/cpp-build:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/cpp-build:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/cpp-build:buildcache,mode=max
          load: true
